// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9rZ5hesTVKT5Ojo7Jlpy6WRmdhUnWRks',
    appId: '1:483389684324:web:653c05c4a6bad858f7bd71',
    messagingSenderId: '483389684324',
    projectId: 'ride-sharing-app-c07e7',
    authDomain: 'ride-sharing-app-c07e7.firebaseapp.com',
    storageBucket: 'ride-sharing-app-c07e7.appspot.com',
    measurementId: 'G-ZKV59DBLYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuMIvq3Nm_WONfPioHVJsUZ3PFb0Bee0Y',
    appId: '1:483389684324:android:28047a1d37f4d44bf7bd71',
    messagingSenderId: '483389684324',
    projectId: 'ride-sharing-app-c07e7',
    storageBucket: 'ride-sharing-app-c07e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJgtk9yRAt0udP1fNocC78uxgbosW1Xpo',
    appId: '1:483389684324:ios:b26db1813513fd8ff7bd71',
    messagingSenderId: '483389684324',
    projectId: 'ride-sharing-app-c07e7',
    storageBucket: 'ride-sharing-app-c07e7.appspot.com',
    iosClientId: '483389684324-gh94bsuj3ec09od5mu3pco5s67hg3239.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJgtk9yRAt0udP1fNocC78uxgbosW1Xpo',
    appId: '1:483389684324:ios:b26db1813513fd8ff7bd71',
    messagingSenderId: '483389684324',
    projectId: 'ride-sharing-app-c07e7',
    storageBucket: 'ride-sharing-app-c07e7.appspot.com',
    iosClientId: '483389684324-gh94bsuj3ec09od5mu3pco5s67hg3239.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideShare',
  );
}
